[project]
name = "alfie"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "autogluon>=1.4.0",
    "dotenv>=0.9.9",
    "fastapi>=0.124.4",
    "flask>=3.1.2",
    "matplotlib>=3.10.8",
    "matplotlib-inline>=0.2.1",
    "seaborn>=0.13.2",
    "shap>=0.49.1",
]
